baseURL: "/"
title: Mingpu Xiao

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Teaching
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3

params:
    description: "Academic website of Mingpu Xiao, PhD Candidate in Political Science at UC San Diego."
    author: Mingpu Xiao
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","teaching","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Mingpu Xiao
          subtitle: "PhD Candidate in Political Science at UC San Diego. My research focuses on political economy, public opinion, and authoritarian politics, with a particular interest in state ownership, economic ideology, and nationalism in contemporary China."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Teaching
              url: teaching/
            - name: Data
              url: data/

      
 

    socialIcons:
        - name: Email
          url: mixiao@ucsd.edu
        - name: GitHub
          url: https://github.com/mingpuxiao
        - name: CV
          url: cv.pdf



    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Mingpu Xiao"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
